### PR TITLE
Feature/add open graph and twitter meta tags 

### LINKED ISSUE #16: Fix the OG tags
# Description

* While sharing AlgoHunt URL on any social media currently we get reactjs icon but actually it should be AlgoHunt logo. So it will be easily fix by adding OG tags.

image

### PR DESCRIPTION
**Pull request by shutter-codes**
eat: Add Open Graph and Twitter meta tags for social media sharing

issue : Fix the OG tags https://github.com/Jai-Marothiya/AlgoHub/issues/16

Added Open Graph meta tags for better link previews on Facebook and LinkedIn
Added Twitter Card meta tags for optimized sharing on Twitter
Included the AlgoHunt logo as the image for social sharing
Screenshot (71)

### CODE REVIEW

**Comment by Jai-Marothiya** [comment]
@shutter-codes - Did you tested out it properly? Because it is not working on whatsapp. This PR preview deploy link: https://deploy-preview-20--algohub-taya.netlify.app/auth
image

**Comment by shutter-codes** [comment]
It was working well on my system.
Kindly wait to load it.

**Comment by shutter-codes** [comment]
Hi jai,
can you  please store the logo in server and share the link of that so i can add it to the image url to make it visible in realtime as whatsapp is not able to trace the location of public folder sometime.

**Comment by shutter-codes** [comment]
Hey i have fixed the issue.

**Comment by shutter-codes** [comment]
Screenshot (231)

**Comment by Jai-Marothiya** [comment]
Thanks for fixing it but please update the PUBLIC_URL with this one: https://algohunt.in because this url https://deploy-preview-20--algohub-taya.netlify.app/  is only for testing purpose. Once you make changes I'll merge your PR.

**Comment by Jai-Marothiya** [comment]
Congratulations for your first contribution in AlgoHunt. 🥳🥳

**Comment by shutter-codes** [comment]
Thank you so much for considering my PR.

**Pull request merged**
